-- Beetlepedia schema: group → genus → taxon, with sources, images, countries and areas.
-- Localized texts are stored as <attribute>_ko / _en / _ja columns.
-- Written for H2 (development, tests) and PostgreSQL.
-- No CHECK constraints: with H2 2.4 every insert into a table with a check constraint created by this
-- migration failed ("Check constraint invalid" caused by "The database has been closed"). Taxon ranks are
-- guaranteed by TaxonRankConverter instead, and the position columns are maintained by Hibernate.

create table source (
    id varchar(64) not null,
    title varchar(500) not null,
    url varchar(1000),
    primary key (id)
);

create table image (
    id bigint generated by default as identity,
    alt_en varchar(4000),
    alt_ja varchar(4000),
    alt_ko varchar(4000),
    author varchar(300) not null,
    file varchar(300) not null unique,
    license varchar(100) not null,
    license_url varchar(500),
    white boolean not null,
    primary key (id)
);

create table country (
    code varchar(8) not null,
    name_en varchar(4000),
    name_ja varchar(4000),
    name_ko varchar(4000),
    primary key (code)
);

create table map_region (
    id varchar(32) not null,
    name_en varchar(4000),
    name_ja varchar(4000),
    name_ko varchar(4000),
    primary key (id)
);

create table area (
    code varchar(48) not null,
    box_lat_max float(53),
    box_lat_min float(53),
    box_lon_max float(53),
    box_lon_min float(53),
    name_en varchar(4000),
    name_ja varchar(4000),
    name_ko varchar(4000),
    point_lat float(53),
    point_lon float(53),
    primary key (code)
);

create table area_country (
    area_code varchar(48) not null,
    country_code varchar(8) not null,
    primary key (country_code, area_code)
);

create table area_exclude (
    area_code varchar(48) not null,
    position integer not null,
    excludes_lat_max float(53),
    excludes_lat_min float(53),
    excludes_lon_max float(53),
    excludes_lon_min float(53),
    primary key (position, area_code)
);

create table base_rank (
    id bigint generated by default as identity,
    position integer not null,
    common_en varchar(4000),
    common_ja varchar(4000),
    common_ko varchar(4000),
    name varchar(255) not null,
    rank_en varchar(4000),
    rank_ja varchar(4000),
    rank_ko varchar(4000),
    primary key (id)
);

create table taxon_group (
    id varchar(32) not null,
    authority varchar(255),
    body_en varchar(4000),
    body_ja varchar(4000),
    body_ko varchar(4000),
    color varchar(7) not null,
    lead_en varchar(4000),
    lead_ja varchar(4000),
    lead_ko varchar(4000),
    name_en varchar(4000),
    name_ja varchar(4000),
    name_ko varchar(4000),
    sci varchar(255) not null,
    sort_order integer not null,
    primary key (id)
);

create table group_rank (
    group_id varchar(32) not null,
    position integer not null,
    ranks_common_en varchar(4000),
    ranks_common_ja varchar(4000),
    ranks_common_ko varchar(4000),
    ranks_name varchar(255) not null,
    ranks_rank_en varchar(4000),
    ranks_rank_ja varchar(4000),
    ranks_rank_ko varchar(4000),
    primary key (position, group_id)
);

create table group_source (
    group_id varchar(32) not null,
    position integer not null,
    source_id varchar(64) not null,
    primary key (position, group_id)
);

create table genus (
    id varchar(32) not null,
    group_id varchar(32) not null,
    hero_image_id bigint,
    map_region_id varchar(32) not null,
    overview_image_id bigint,
    authority varchar(255),
    color varchar(7) not null,
    conservation_en varchar(4000),
    conservation_ja varchar(4000),
    conservation_ko varchar(4000),
    dimorphism_en varchar(4000),
    dimorphism_ja varchar(4000),
    dimorphism_ko varchar(4000),
    eyebrow_en varchar(4000),
    eyebrow_ja varchar(4000),
    eyebrow_ko varchar(4000),
    food_en varchar(4000),
    food_ja varchar(4000),
    food_ko varchar(4000),
    lead_en varchar(4000),
    lead_ja varchar(4000),
    lead_ko varchar(4000),
    lifecycle_lead_en varchar(4000),
    lifecycle_lead_ja varchar(4000),
    lifecycle_lead_ko varchar(4000),
    name_en varchar(4000),
    name_ja varchar(4000),
    name_ko varchar(4000),
    overview_body_en varchar(4000),
    overview_body_ja varchar(4000),
    overview_body_ko varchar(4000),
    overview_kicker_en varchar(4000),
    overview_kicker_ja varchar(4000),
    overview_kicker_ko varchar(4000),
    sci varchar(255) not null unique,
    season_en varchar(4000),
    season_ja varchar(4000),
    season_ko varchar(4000),
    short_name_en varchar(4000),
    short_name_ja varchar(4000),
    short_name_ko varchar(4000),
    sort_order integer not null,
    species_note_en varchar(4000),
    species_note_ja varchar(4000),
    species_note_ko varchar(4000),
    weights_note_en varchar(4000),
    weights_note_ja varchar(4000),
    weights_note_ko varchar(4000),
    primary key (id)
);

create table genus_rank (
    genus_id varchar(32) not null,
    position integer not null,
    ranks_common_en varchar(4000),
    ranks_common_ja varchar(4000),
    ranks_common_ko varchar(4000),
    ranks_name varchar(255) not null,
    ranks_rank_en varchar(4000),
    ranks_rank_ja varchar(4000),
    ranks_rank_ko varchar(4000),
    primary key (position, genus_id)
);

create table genus_hero_stat (
    genus_id varchar(32) not null,
    position integer not null,
    hero_stats_figure varchar(255) not null,
    hero_stats_label_en varchar(4000),
    hero_stats_label_ja varchar(4000),
    hero_stats_label_ko varchar(4000),
    hero_stats_unit varchar(255),
    primary key (position, genus_id)
);

create table genus_overview_card (
    genus_id varchar(32) not null,
    position integer not null,
    overview_cards_text_en varchar(4000),
    overview_cards_text_ja varchar(4000),
    overview_cards_text_ko varchar(4000),
    overview_cards_title_en varchar(4000),
    overview_cards_title_ja varchar(4000),
    overview_cards_title_ko varchar(4000),
    primary key (position, genus_id)
);

create table genus_lifecycle_stage (
    genus_id varchar(32) not null,
    position integer not null,
    lifecycle_stages_stage varchar(16) not null,
    lifecycle_stages_text_en varchar(4000),
    lifecycle_stages_text_ja varchar(4000),
    lifecycle_stages_text_ko varchar(4000),
    lifecycle_stages_time_en varchar(4000),
    lifecycle_stages_time_ja varchar(4000),
    lifecycle_stages_time_ko varchar(4000),
    lifecycle_stages_title_en varchar(4000),
    lifecycle_stages_title_ja varchar(4000),
    lifecycle_stages_title_ko varchar(4000),
    primary key (position, genus_id)
);

create table genus_care (
    genus_id varchar(32) not null,
    position integer not null,
    care_en varchar(4000),
    care_ja varchar(4000),
    care_ko varchar(4000),
    primary key (position, genus_id)
);

create table genus_fact (
    genus_id varchar(32) not null,
    position integer not null,
    facts_en varchar(4000),
    facts_ja varchar(4000),
    facts_ko varchar(4000),
    primary key (position, genus_id)
);

create table genus_latin_term (
    genus_id varchar(32) not null,
    position integer not null,
    term varchar(255) not null,
    primary key (position, genus_id)
);

create table genus_size_default (
    genus_id varchar(32) not null,
    position integer not null,
    taxon_id varchar(64) not null,
    primary key (position, genus_id)
);

create table genus_weight (
    id bigint generated by default as identity,
    genus_id varchar(32) not null,
    position integer,
    approx boolean not null,
    color varchar(7),
    estimate boolean not null,
    label_en varchar(4000),
    label_ja varchar(4000),
    label_ko varchar(4000),
    note_en varchar(4000),
    note_ja varchar(4000),
    note_ko varchar(4000),
    plus boolean not null,
    reported boolean not null,
    weight_grams float(53) not null,
    primary key (id)
);

create table genus_weight_source (
    position integer not null,
    source_id varchar(64) not null,
    weight_id bigint not null,
    primary key (position, weight_id)
);

create table species_info (
    id bigint generated by default as identity,
    genus_id varchar(32) not null,
    position integer,
    authority varchar(255),
    name_en varchar(4000),
    name_ja varchar(4000),
    name_ko varchar(4000),
    species_sci varchar(255) not null,
    text_en varchar(4000),
    text_ja varchar(4000),
    text_ko varchar(4000),
    primary key (id)
);

create table species_info_source (
    position integer not null,
    source_id varchar(64) not null,
    species_info_id bigint not null,
    primary key (position, species_info_id)
);

create table genus_source (
    genus_id varchar(32) not null,
    position integer not null,
    source_id varchar(64) not null,
    primary key (position, genus_id)
);

create table taxon (
    id varchar(64) not null,
    genus_id varchar(32) not null,
    model3d_model_id varchar(255),
    authority varchar(255),
    captivity_note_en varchar(4000),
    captivity_note_ja varchar(4000),
    captivity_note_ko varchar(4000),
    color varchar(7) not null,
    conservation_status_en varchar(4000),
    conservation_status_ja varchar(4000),
    conservation_status_ko varchar(4000),
    conservation_text_en varchar(4000),
    conservation_text_ja varchar(4000),
    conservation_text_ko varchar(4000),
    described_year integer,
    dimorphism_en varchar(4000),
    dimorphism_ja varchar(4000),
    dimorphism_ko varchar(4000),
    distribution_note_en varchar(4000),
    distribution_note_ja varchar(4000),
    distribution_note_ko varchar(4000),
    ecology_en varchar(4000),
    ecology_ja varchar(4000),
    ecology_ko varchar(4000),
    food_en varchar(4000),
    food_ja varchar(4000),
    food_ko varchar(4000),
    habitat_en varchar(4000),
    habitat_ja varchar(4000),
    habitat_ko varchar(4000),
    model3d_author varchar(255),
    model3d_license varchar(255),
    model3d_url varchar(1000),
    morphology_en varchar(4000),
    morphology_ja varchar(4000),
    morphology_ko varchar(4000),
    name_en varchar(4000),
    name_informal_en boolean,
    name_informal_ja boolean,
    name_informal_ko boolean,
    name_ja varchar(4000),
    name_ko varchar(4000),
    name_note_en varchar(4000),
    name_note_ja varchar(4000),
    name_note_ko varchar(4000),
    pattern_en varchar(4000),
    pattern_ja varchar(4000),
    pattern_ko varchar(4000),
    taxon_rank varchar(16) not null,
    sci varchar(255) not null unique,
    season_en varchar(4000),
    season_ja varchar(4000),
    season_ko varchar(4000),
    size_female_max float(53),
    size_female_min float(53),
    size_male_max float(53),
    size_male_min float(53),
    size_note_en varchar(4000),
    size_note_ja varchar(4000),
    size_note_ko varchar(4000),
    sort_order integer not null,
    species_sci varchar(255),
    primary key (id)
);

create table taxon_range (
    code varchar(48) not null,
    position integer not null,
    taxon_id varchar(64) not null,
    primary key (position, taxon_id)
);

create table taxon_subspecies (
    position integer not null,
    taxon_id varchar(64) not null,
    subspecies_authority varchar(255),
    subspecies_note_en varchar(4000),
    subspecies_note_ja varchar(4000),
    subspecies_note_ko varchar(4000),
    subspecies_sci varchar(255) not null,
    primary key (position, taxon_id)
);

create table taxon_history (
    position integer not null,
    taxon_id varchar(64) not null,
    event_year integer,
    history_text_en varchar(4000),
    history_text_ja varchar(4000),
    history_text_ko varchar(4000),
    primary key (position, taxon_id)
);

create table taxon_fact (
    position integer not null,
    taxon_id varchar(64) not null,
    facts_en varchar(4000),
    facts_ja varchar(4000),
    facts_ko varchar(4000),
    primary key (position, taxon_id)
);

create table taxon_issue (
    id bigint generated by default as identity,
    position integer,
    taxon_id varchar(64) not null,
    text_en varchar(4000),
    text_ja varchar(4000),
    text_ko varchar(4000),
    title_en varchar(4000),
    title_ja varchar(4000),
    title_ko varchar(4000),
    primary key (id)
);

create table taxon_issue_source (
    issue_id bigint not null,
    position integer not null,
    source_id varchar(64) not null,
    primary key (position, issue_id)
);

create table taxon_image (
    image_id bigint not null,
    position integer not null,
    taxon_id varchar(64) not null,
    primary key (position, taxon_id)
);

create table taxon_size_source (
    position integer not null,
    source_id varchar(64) not null,
    taxon_id varchar(64) not null,
    primary key (position, taxon_id)
);

create table taxon_source (
    position integer not null,
    source_id varchar(64) not null,
    taxon_id varchar(64) not null,
    primary key (position, taxon_id)
);

-- Foreign keys
alter table area_country add constraint fk_area_country_area_code foreign key (area_code) references area;
alter table area_exclude add constraint fk_area_exclude_area_code foreign key (area_code) references area;
alter table group_rank add constraint fk_group_rank_group_id foreign key (group_id) references taxon_group;
alter table group_source add constraint fk_group_source_source_id foreign key (source_id) references source;
alter table group_source add constraint fk_group_source_group_id foreign key (group_id) references taxon_group;
alter table genus add constraint fk_genus_group_id foreign key (group_id) references taxon_group;
alter table genus add constraint fk_genus_hero_image_id foreign key (hero_image_id) references image;
alter table genus add constraint fk_genus_map_region_id foreign key (map_region_id) references map_region;
alter table genus add constraint fk_genus_overview_image_id foreign key (overview_image_id) references image;
alter table genus_rank add constraint fk_genus_rank_genus_id foreign key (genus_id) references genus;
alter table genus_hero_stat add constraint fk_genus_hero_stat_genus_id foreign key (genus_id) references genus;
alter table genus_overview_card add constraint fk_genus_overview_card_genus_id foreign key (genus_id) references genus;
alter table genus_lifecycle_stage add constraint fk_genus_lifecycle_stage_genus_id foreign key (genus_id) references genus;
alter table genus_care add constraint fk_genus_care_genus_id foreign key (genus_id) references genus;
alter table genus_fact add constraint fk_genus_fact_genus_id foreign key (genus_id) references genus;
alter table genus_latin_term add constraint fk_genus_latin_term_genus_id foreign key (genus_id) references genus;
alter table genus_size_default add constraint fk_genus_size_default_genus_id foreign key (genus_id) references genus;
alter table genus_weight add constraint fk_genus_weight_genus_id foreign key (genus_id) references genus;
alter table genus_weight_source add constraint fk_genus_weight_source_source_id foreign key (source_id) references source;
alter table genus_weight_source add constraint fk_genus_weight_source_weight_id foreign key (weight_id) references genus_weight;
alter table species_info add constraint fk_species_info_genus_id foreign key (genus_id) references genus;
alter table species_info_source add constraint fk_species_info_source_source_id foreign key (source_id) references source;
alter table species_info_source add constraint fk_species_info_source_species_info_id foreign key (species_info_id) references species_info;
alter table genus_source add constraint fk_genus_source_source_id foreign key (source_id) references source;
alter table genus_source add constraint fk_genus_source_genus_id foreign key (genus_id) references genus;
alter table taxon add constraint fk_taxon_genus_id foreign key (genus_id) references genus;
alter table taxon_range add constraint fk_taxon_range_taxon_id foreign key (taxon_id) references taxon;
alter table taxon_subspecies add constraint fk_taxon_subspecies_taxon_id foreign key (taxon_id) references taxon;
alter table taxon_history add constraint fk_taxon_history_taxon_id foreign key (taxon_id) references taxon;
alter table taxon_fact add constraint fk_taxon_fact_taxon_id foreign key (taxon_id) references taxon;
alter table taxon_issue add constraint fk_taxon_issue_taxon_id foreign key (taxon_id) references taxon;
alter table taxon_issue_source add constraint fk_taxon_issue_source_source_id foreign key (source_id) references source;
alter table taxon_issue_source add constraint fk_taxon_issue_source_issue_id foreign key (issue_id) references taxon_issue;
alter table taxon_image add constraint fk_taxon_image_image_id foreign key (image_id) references image;
alter table taxon_image add constraint fk_taxon_image_taxon_id foreign key (taxon_id) references taxon;
alter table taxon_size_source add constraint fk_taxon_size_source_source_id foreign key (source_id) references source;
alter table taxon_size_source add constraint fk_taxon_size_source_taxon_id foreign key (taxon_id) references taxon;
alter table taxon_source add constraint fk_taxon_source_source_id foreign key (source_id) references source;
alter table taxon_source add constraint fk_taxon_source_taxon_id foreign key (taxon_id) references taxon;

-- Indexes for lookups by parent
create index ix_area_country_area_code on area_country (area_code);
create index ix_area_exclude_area_code on area_exclude (area_code);
create index ix_genus_group_id on genus (group_id);
create index ix_genus_hero_image_id on genus (hero_image_id);
create index ix_genus_map_region_id on genus (map_region_id);
create index ix_genus_overview_image_id on genus (overview_image_id);
create index ix_genus_care_genus_id on genus_care (genus_id);
create index ix_genus_fact_genus_id on genus_fact (genus_id);
create index ix_genus_hero_stat_genus_id on genus_hero_stat (genus_id);
create index ix_genus_latin_term_genus_id on genus_latin_term (genus_id);
create index ix_genus_lifecycle_stage_genus_id on genus_lifecycle_stage (genus_id);
create index ix_genus_overview_card_genus_id on genus_overview_card (genus_id);
create index ix_genus_rank_genus_id on genus_rank (genus_id);
create index ix_genus_size_default_genus_id on genus_size_default (genus_id);
create index ix_genus_source_source_id on genus_source (source_id);
create index ix_genus_source_genus_id on genus_source (genus_id);
create index ix_genus_weight_genus_id on genus_weight (genus_id);
create index ix_genus_weight_source_source_id on genus_weight_source (source_id);
create index ix_genus_weight_source_weight_id on genus_weight_source (weight_id);
create index ix_group_rank_group_id on group_rank (group_id);
create index ix_group_source_source_id on group_source (source_id);
create index ix_group_source_group_id on group_source (group_id);
create index ix_species_info_genus_id on species_info (genus_id);
create index ix_species_info_source_source_id on species_info_source (source_id);
create index ix_species_info_source_species_info_id on species_info_source (species_info_id);
create index ix_taxon_genus_id on taxon (genus_id);
create index ix_taxon_fact_taxon_id on taxon_fact (taxon_id);
create index ix_taxon_history_taxon_id on taxon_history (taxon_id);
create index ix_taxon_image_image_id on taxon_image (image_id);
create index ix_taxon_image_taxon_id on taxon_image (taxon_id);
create index ix_taxon_issue_taxon_id on taxon_issue (taxon_id);
create index ix_taxon_issue_source_source_id on taxon_issue_source (source_id);
create index ix_taxon_issue_source_issue_id on taxon_issue_source (issue_id);
create index ix_taxon_range_taxon_id on taxon_range (taxon_id);
create index ix_taxon_size_source_source_id on taxon_size_source (source_id);
create index ix_taxon_size_source_taxon_id on taxon_size_source (taxon_id);
create index ix_taxon_source_source_id on taxon_source (source_id);
create index ix_taxon_source_taxon_id on taxon_source (taxon_id);
create index ix_taxon_subspecies_taxon_id on taxon_subspecies (taxon_id);
